In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
# 파이토치의 기본적인 모델 flow 구조

class Net(nn.Module):
    
    # 사용할 파라미터를 정의함 (neural net, convnet, lstm, 등등)
    def __init__(self):
        super(Net, self).__init__()
        # nn.Linear : 일반적인 뉴럴 네트워크
        self.fc1 = nn.Linear(20, 30)
        self.fc2 = nn.Linear(30, 40)
        self.fc3 = nn.Linear(40, 10)
        
    # 실제로 값이 통과하는 부분 (연산 작업들은 forward에서 진행)
    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
        return x
        
        

In [3]:
net = Net()

In [4]:
# 모델 구조 파악
net

Net(
  (fc1): Linear(in_features=20, out_features=30, bias=True)
  (fc2): Linear(in_features=30, out_features=40, bias=True)
  (fc3): Linear(in_features=40, out_features=10, bias=True)
)

In [5]:
# 파라미터 직접 보기
net.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 1.1906e-01,  1.6910e-01, -9.1122e-02,  3.4714e-02, -1.6478e-01,
                        9.9557e-02, -8.0940e-03, -2.0241e-01,  1.5856e-01,  1.8645e-01,
                       -1.7109e-01,  1.7156e-01, -1.5311e-01, -1.9251e-02,  4.0418e-02,
                        2.5517e-02,  1.1981e-01,  3.6317e-02, -1.7923e-01, -7.3755e-03],
                      [ 7.9305e-02,  1.9931e-01, -2.0366e-01,  1.1967e-01, -4.0301e-02,
                        2.6372e-02,  1.5090e-01, -1.1800e-02,  1.5825e-01, -8.0637e-03,
                        1.5298e-04, -8.1806e-02, -2.1689e-01,  9.1072e-02, -1.5573e-01,
                       -2.1730e-01,  8.6066e-03, -1.0245e-01, -1.6658e-01,  1.5077e-01],
                      [ 2.1585e-01,  1.6078e-02, -6.4705e-02,  1.1412e-01,  1.8840e-01,
                       -2.3172e-02, -1.2647e-01, -1.3991e-01,  9.3556e-02, -8.3779e-02,
                        1.3438e-01,  1.4214e-01,  1.8364e-01, -1.3793e-01, -3.8780e-02,
  

In [6]:
# dimension size check하는 방법 (굉장히 많이 씀)
net.state_dict()['fc2.weight'].size()

torch.Size([40, 30])

In [7]:
# 20 앞의 숫자는 batch size

input_x = torch.randn(1, 20)
input_x

tensor([[-0.0454,  0.4530,  0.4766,  1.0096,  1.2725, -0.2080, -1.8094, -0.3082,
         -0.3205,  0.8400,  1.6714, -0.9516, -1.2532, -0.6099,  0.1904, -0.5120,
         -0.4534, -0.9616, -0.4912,  1.2027]])

In [8]:
# input_x가 네트워크를 통과한 값
out = net(input_x)
out

tensor([[-0.1866,  0.0404, -0.1266, -0.1912,  0.0623,  0.0052, -0.1457, -0.0735,
         -0.0603, -0.1852]], grad_fn=<AddmmBackward>)

In [9]:
target = torch.ones(1,10)
target

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
# grad 계산 & weight 학습하는 과정
import torch.optim as optim

# 사용할 optimizer 정의 
# 가장 단순한 optimizer : Stochastic Gradient Descent
# 이 외에도 Adam, RMSProp... 등등이 있음
optimizer = optim.SGD(net.parameters(), lr=0.01)

# gradient 초기화
optimizer.zero_grad()

# output 뽑기
out = net(input_x)

# loss function 정의
criterion = nn.MSELoss()
# out, target 사이의 loss 계산
loss = criterion(out, target)
print(f"Loss : {loss}")

# loss 역전파 및 그래디언트 계산
loss.backward()
# weight 업데이트
optimizer.step()


Loss : 1.1879945993423462


In [12]:
loss

tensor(1.1880, grad_fn=<MseLossBackward>)

In [ ]:
for i in range(1000):
    optimizer.zero_grad()
    out = net(input_x)
    loss = criterion(out, target)
    if i % 10 == 0:
        print(loss)
    loss.backward()
    optimizer.step()

In [ ]:
# 파이토치 layer 어떤식으로 진행되는지 테스트
fc1 = nn.Linear(2, 3)
print(fc1.state_dict())
x = torch.rand((1,2))
x

In [ ]:
x = fc1(x)
x

In [ ]:
x = F.relu(x)
x