In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = [1,2,3]

In [9]:
type(a)

numpy.ndarray

In [12]:
a

array([1, 2, 3])

In [13]:
print(a[0], a[1], a[2])

1 2 3


In [15]:
a[0] = 7

In [17]:
a

array([7, 2, 3])

In [18]:
b = np.array([ [1, 2, 3] , [4, 5, 6] ])

In [21]:
b.shape

(2, 3)

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.zeros([2,3]) + 7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [27]:
np.full([2,3], 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [29]:
np.random.random([2,3])

array([[0.76948965, 0.25338356, 0.15816782],
       [0.21289546, 0.37683709, 0.27086574]])

In [73]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
# a[np.arange(3), 2]
a[:, -2:] = a[:, -2:] + 1
a[:, -2:] += 1
a

array([[ 1,  2,  5,  6],
       [ 5,  6,  9, 10],
       [ 9, 10, 13, 14]])

In [69]:
a[:, -2:]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [76]:
# np.arange(10)
np.arange(4, 7)

array([4, 5, 6])

In [77]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [78]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
bool_idx = (a > 4)

In [82]:
bool_idx

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
a[bool_idx]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
a[a > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
x = np.array([1, 2])
x.dtype

dtype('int64')

In [91]:
x = x.astype('int64')

In [93]:
x.dtype

dtype('int64')

In [100]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [108]:
# Element-wise
# + - * /
x * y

array([[ 5, 12],
       [21, 32]])

In [110]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [112]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
np.sum(x)

21

In [114]:
np.sum(x, axis=0)

array([5, 7, 9])

In [115]:
np.sum(x, axis=1)

array([ 6, 15])

In [117]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [124]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
# 2 * 3 = 6개
x.shape

(2, 3)

In [142]:
x.reshape((3, -1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [155]:
test = np.array(np.arange(28*28)).reshape(28,28)
test.shape

(28, 28)